[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
unfixable = ["F401"]

[tool.ruff]
line-length = 120
ignore-init-module-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true